### ISSUE TITLE
view_df is not a valid viewframe or incompatible

### ISSUE THREAD

**Issue by ratheraarif** [open2c/cooltools#439] opened 2023-05-02 16:23 UTC
I am trying to replicate the results of the notebook https://cooltools.readthedocs.io/en/latest/notebooks/contacts_vs_distance.html on the test dataset. When executing the following code 

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/46924431/235726580-c930b757-f7a6-4247-b138-18b13d23bece.png">

It throws an error view_df is not a valid viewframe or incompatible. 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/46924431/235726893-ef076d39-cfcb-401b-ad6f-5641d81ed28e.png">

**Comment by gfudenberg** [comment] 2023-05-02 19:02
hi Arif, 
what version of cooltools/cooler/bioframe are you using? 
can you also print the view_df?
Thanks!

**Comment by baishengjun** [comment] 2023-05-04 10:40
same error; with cooler==0.9.1, cooltools==0.5.4, bioframe==0.4.1

**Comment by gfudenberg** [comment] 2023-05-18 18:47
hi Arif, sorry for the slow reply. 

I am unable to reproduce the error with the same versions of those packages, python==3.8, and pandas==1.5.1, numpy==1.23.0.

from the snippet that you posted, I seem to see chrM in the view_df in the cell above. The test cooler only has data for chromosomes 2 & 17, which could be leading to the incompatibility. 

I get the following for the filtered hg38_arms dataframe, which is then used as the view_df for P(s):
<img width="748" alt="image" src="https://github.com/open2c/cooltools/assets/19657573/b3b201c0-9bd6-46a1-a75d-23e875ab9fc4">
 
Can you verify that you are filtering chromosomes such that they are consistent with the test cooler provided?

Thanks!

**Comment by gfudenberg** [comment] 2023-10-09 19:13
closing for now as it has been a few months without a reply, but feel free to re-open

**Closed by gfudenberg** 2023-10-09 19:13 UTC
