### ISSUE TITLE
expected API: transforms and weights

### ISSUE THREAD

**Issue by golobor** [open2c/cooltools#191] opened 2020-10-11 11:44 UTC
Issue: the current API for diagsums is tricky to use and non-transparent. Balancing is not done by default and requires a dict of lambda functions 😱 , it also doesn't mention that raw pixel sums are calculated over valid pixels only.

Suggestions:
1. If `weight_col` argument is None, return two columns "count.sum" and "n" which returns the sum over **all** pixels in the diagonal and the total number of pixels in this diagonal.
2. If `weight_col` is specified, all three more columns "count_valid.sum", "n_valid" and "balanced.sum", containing the sum of counts over valid pixels, number of valid pixels in the diagonal and the sum of balanced weights.
3. Have `weight_col` set to "weight" by default. 

Only one weight column thus will be used for balancing. This should cover a majority of use cases. If a user wants to try multiple weight columns, they can either run diagsum multiple times or add a custom transform. 
Of course, this requires yet another minor change of the API (I volunteer to take care of that), but the advantage is that it'll be more transparent with regard to masking.

**Comment by gfudenberg** [comment] 2021-11-04 17:30
was this resolved in latest commit @sergpolly cc @golobor ?

**Comment by sergpolly** [comment] 2021-11-04 18:27
in a way this addressed, because we've wrapped `diagsum/blocks` into resurrected `get_cis_expected` and `get_trans_expected` - so - no more lambda functions as a function input. And overall API should more friendly.
Underlying `diagsum/blocksum` are largely unchanged from API standpoint.


 the second point though:
> If weight_col is specified, all three more columns "count_valid.sum", "n_valid" and "balanced.sum", containing the sum of counts over valid pixels, number of valid pixels in the diagonal and the sum of balanced weights.

isn't fully addressed, as I'm not sure if we report/calculate `count_valid.sum` when working on balanced data ...
We definitely need to document this better ! i.e. just say it clearly if `count.sum` (raw counts) are affected by the balancing weights or not

we'll do in the next batch of small fixes for expected

**Comment by sergpolly** [comment] 2021-11-05 05:33
woof

> If weight_col argument is None, return two columns "count.sum" and "n" which returns the sum over all pixels in the diagonal and the total number of pixels in this diagonal.

this is current behavior, and has been like that for some time, confirmed added test for that

> If weight_col is specified, all three more columns "count_valid.sum", "n_valid" and "balanced.sum", containing the sum of counts over valid pixels, number of valid pixels in the diagonal and the sum of balanced weights.

this is current behavior as well - checked , added test. There was a moment when this wasn't true actually - my bad
the only difference, count_valid.sum is still called count.sum

> Have weight_col set to "weight" by default.

has been like that for a long time

**Comment by sergpolly** [comment] 2021-11-05 05:35
consider resolved in #296

**Comment by gfudenberg** [comment] 2021-11-11 00:55
closing since merged!

**Closed by gfudenberg** 2021-11-11 00:55 UTC
