### ISSUE TITLE
Making saddle plots from a cool file converted from .hic format

### ISSUE THREAD

**Issue by akriz** [open2c/cooltools#174] opened 2020-07-12 21:09 UTC
Hello,

I'm following your very nice documentation on how to generate a Saddle Plot from Hi-C data  (https://cooltools.readthedocs.io/en/latest/notebooks/04_saddle-plots.html). I'm using a cool file which I've converted from .hic format using the hic2cool tool.

I noticed many errors pop up due to python scripts expecting the normalization vector column to be named 'weight', e.g. scripts including lines like:

weight_name="weight"

However, for a cool file converted from .hic format, there is no "weight" column but instead several normalization columns named "VC", "VC_SQRT", and "KR". So I was able to fix this issue by going into the python scripts and changing the corresponding lines to expect the weight column to be named "KR" (for example) instead, e.g.

weight_name="KR"

I was wondering if I need to alter the scripts further to account for the differing nature of "KR" values versus "weight" values? For example, I read in the hic2cool documentation that "KR" values are divisive as opposed to the "weight" values, which are multiplicative.

Please let me know if any more information would help.

Thank you!

**Comment by Phlya** [comment] 2021-11-03 19:37
Basically duplicate of https://github.com/open2c/cooltools/issues/173, it is mostly solved, closing this one.

**Closed by Phlya** 2021-11-03 19:37 UTC
Labels: duplicate
